#!/bin/bash
# ============================================================
# sync_intraday.sh — 生成 cron 侧 intraday_monitor.py（AUTO-GENERATED）
#
# 源文件（唯一编辑点）:
#   skills/stock/stock-expert/skills/feishu-bitable/intraday_monitor.py
# 编译产物（cron 执行）:
#   scripts/cron/intraday_monitor.py
#
# 产物 = 自动生成 header（sys.path + atexit gate）+ 源文件全文
# 漂移检测: cron 侧第 3 行嵌入了源文件 md5，用 sync_intraday.sh --check 校验
# ============================================================
set -e

SRC=/home/caojy/.hermes/profiles/stock/skills/stock/stock-expert/skills/feishu-bitable/intraday_monitor.py
DST=/home/caojy/.hermes/profiles/stock/scripts/cron/intraday_monitor.py
FEISHU_DIR=/home/caojy/.hermes/profiles/stock/skills/stock/stock-expert/skills/feishu-bitable

if [ "$1" = "--check" ]; then
    # 校验 DST 是否是当前 SRC 的编译产物
    EMBEDDED=$(sed -n '2p' "$DST" | grep -o 'src_md5=[a-f0-9]*' | cut -d= -f2)
    CURRENT=$(md5sum "$SRC" | cut -d' ' -f1)
    if [ "$EMBEDDED" = "$CURRENT" ]; then
        echo "IN-SYNC: src_md5=$CURRENT"
        exit 0
    else
        echo "DRIFT DETECTED: dst embedded src_md5=$EMBEDDED, current src_md5=$CURRENT"
        echo "Run: bash $0  (to re-sync)"
        exit 1
    fi
fi

SRC_MD5=$(md5sum "$SRC" | cut -d' ' -f1)
mkdir -p "$(dirname "$DST")"
{
    echo "# AUTO-GENERATED by scripts/cron/sync_intraday.sh — DO NOT EDIT THIS FILE"
    echo "# source: $SRC  (src_md5=$SRC_MD5)"
    echo "# usage: bash sync_intraday.sh to re-sync; bash sync_intraday.sh --check to verify"
    echo "import sys, atexit"
    echo "sys.path.insert(0, '$FEISHU_DIR')"
    echo "atexit.register(lambda: print('{\"wakeAgent\": false}', flush=True))"
    echo "# --- END AUTO-GENERATED HEADER ---"
    cat "$SRC"
} > "$DST"

python3 -m py_compile "$DST"
echo "synced: dst_md5=$(md5sum "$DST" | cut -d' ' -f1) src_md5=$SRC_MD5"
